[[redirects]]
  from = "https://sitnikru.netlify.com/*"
  to = "https://sitnik.ru/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/ru"
  conditions = { Language = ["ru"] }
  status = 302

[[redirects]]
  from = "/"
  to = "/en"
  status = 302

[[headers]]
  for = "*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "connect-src 'self' https://evilmartians.com/ https://maps.googleapis.com/; object-src 'none'; frame-ancestors 'none'; style-src 'sha256-8tiHv9HLUwW/ivS9G64wenIAL8OaNCb0dgRXyPDH3og='; script-src 'sha256-VP54YLU1KguikBg/AuKa/+S0qQCGTdcrYuqNKF/8IB0=' 'self'"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/photo.*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
