[[redirects]]
  from = "https://sitnikru.netlify.com/*"
  to = "https://sitnik.ru/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/ru"
  conditions = { Language = ["ru"] }
  status = 302

[[redirects]]
  from = "/"
  to = "/en"
  status = 302

[[headers]]
  for = "*"
  [headers.values]
    X-Frame-Options = "deny"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
