[[redirects]]
  from = "https://sitnikru.netlify.com/*"
  to = "https://sitnik.ru/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/ru"
  conditions = { Language = ["ru"] }
  status = 302

[[redirects]]
  from = "/"
  to = "/en"
  status = 302

[[headers]]
  for = "*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "connect-src 'self' https://evilmartians.com/ https://maps.googleapis.com/; object-src 'none'; frame-ancestors 'none'; form-action 'none'; base-uri 'none'; style-src 'sha256-Tu3F9biIkG84/wt/BkY8k6IOWgss0IzUAgnp4cIQ0h4='; script-src 'sha256-kobWgEblrwG+fodFX7SD7tA+Veth130j0wM/6um3xvE=' 'self'"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/photo.*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
