name: Test

on:
  push

env:
  FORCE_COLOR: 2

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install all dependencies
        run: yarn install
      - name: Build and test
        run: yarn test
