name: Update location
on:
  schedule:
    - cron: '28 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.24.0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - name: Check location
        id: location
        run: ./scripts/check-location.js
      - name: Install build dependencies
        if: steps.location.outputs.updated
        run: pnpm install --frozen-lockfile --production
      - name: Update location
        if: steps.location.outputs.updated
        run: ./scripts/update-location.js
        env:
          GMAPS_TOKEN: ${{ secrets.GMAPS_TOKEN }}
          FORCE_COLOR: 2
      - name: Build static files
        if: steps.location.outputs.updated
        run: pnpm build
        env:
          FORCE_COLOR: 2
      - name: Install Google Cloud
        if: steps.location.outputs.updated
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '274.0.1'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
      - name: Deploy files
        if: steps.location.outputs.updated
        run: pnpx ssdeploy deploy
        env:
          GCLOUD_APP: ${{ secrets.GCLOUD_APP }}
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          FORCE_COLOR: 2
